title: Jordan Wong
logo: /assets/headshot_circle.png
description: Engineering graduate passionate about the field of controlled environment agriculture
show_downloads: false
theme: jekyll-theme-minimal
imagesurl: "/jordandood.github.io/assets/"
