title: Jordan Wong
logo: /assets/headshot.png
description: Recent graduate passionate about the field of controlled environment agriculture
show_downloads: false
theme: jekyll-theme-minimal
imagesurl: "/jordandood.github.io/img/"

