title: Jordan Wong
logo: /assets/headshot_circle.png
description: Engineering graduate passionate about the field of controlled environment agriculture
[LinkedIn](https://www.linkedin.com/in/jordanwong3/)
show_downloads: false
theme: jekyll-theme-minimal
imagesurl: "/jordandood.github.io/assets/"
